from setuptools import find_packages, setup

setup(
    name="jira-analytics-dashboard",
    version="0.1.0",
    description="A Streamlit dashboard for JIRA analytics",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "streamlit>=1.24.0",
        "pandas>=1.5.0",
        "numpy>=1.23.0",
        "plotly>=5.13.0",
        "matplotlib>=3.7.0",
        "pytest>=7.3.1",
        "pytest-cov>=4.0.0",
        "pytest-asyncio>=0.23.0",
        "pytest-mock>=3.10.0",
        "black>=22.3.0",
        "flake8>=6.0.0",
        "isort>=5.12.0",
        "mypy>=1.3.0",
        "python-dotenv>=1.0.0",
        "anthropic>=0.3.0",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)
