[browser]
gatherUsageStats = false
serverAddress = "localhost"

[server]
enableCORS = false
enableWebsocketCompression = true
enableXsrfProtection = true
headless = false
maxUploadSize = 200
port = 8501
runOnSave = true

[theme]
base = "light"
primaryColor = "#007DBA"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[logger]
level = "INFO"
messageFormat = "%(asctime)s %(message)s"
