[browser]
gatherUsageStats = false

[server]
enableCORS = true
enableWebsocketCompression = true
enableXsrfProtection = true
headless = true
maxUploadSize = 200
runOnSave = true

[theme]
base = "light"
primaryColor = "#007DBA"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#1E1E1E"
font = "sans serif"

[logger]
level = "INFO"
messageFormat = "%(asctime)s %(message)s"
