[server]
enableCORS = false
runOnSave = true

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[logger]
level = "INFO"

[client]
toolbarMode = "auto"
showErrorDetails = true

[runner]
fastReruns = true
